#  ------------------------------------------------------------
#   Copyright (c) Microsoft Corporation.  All rights reserved.
#   Licensed under the MIT License (MIT). See License.txt in the repo root for license information.
#  ------------------------------------------------------------

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: storageadapter
spec:
  replicas: 1
  minReadySeconds: 10
  strategy:
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: storageadapter
    spec:
      containers:
      - name: storageadapter
        image: azureiotpcs/pcs-storage-adapter-dotnet:testing
        ports:
        - containerPort: 9022
        env:
        - name: PCS_STORAGEADAPTER_WEBSERVICE_PORT
          value: "9022"
        - name: PCS_STORAGEADAPTER_DOCUMENTDB_CONNSTRING
          valueFrom:
            secretKeyRef:
              name: devicesimulation 
              key: CosmosDB_ConnectionString 
---
apiVersion: v1
kind: Service
metadata:
  name: storageadapter
  labels:
    app: storageadapter
spec:
  type: NodePort
  ports:
  - port: 9022
  selector:
    app: storageadapter
